name: odate
channels:
  - conda-forge
dependencies:
  - python=3.13  # Specify your desired Python version
  - pip
  # R base and the R kernel for Jupyter
  - r-base
  - r-irkernel
  # Example R packages
  - r-ggplot2
  # Example Python packages
  - numpy
  - pandas
  - pip:
    - ./odate-extensions/jlab_cell_run-0.1.0-py3-none-any.whl
    - ./odate-extensions/jlab_solarised_dark_theme-0.2.0-py3-none-any.whl
    - ./odate-extensions/jlab_solarised_light_theme-0.2.0-py3-none-any.whl